### ISSUE TITLE
Can't delete collection tags in daily log

### ISSUE THREAD

**Issue by thanhtong010** [cse110-w21-group7/cse110-SP21-group7#357]
**Describe the bug**
After adding a collection tag on the daily log, I cannot delete the tag. I'm not sure if this was an update that we will talk about later in the standup.

**To Reproduce**
1. Go to a daily log entry
2. Add a collection tag
3. See error

**Expected behavior**
Ideally, the collection tag should be able to be deleted by the user.

**Screenshots**
<img width="960" alt="2021-06-08 (12)" src="https://user-images.githubusercontent.com/72485537/121245890-6360dd80-c855-11eb-9243-f3b5398db092.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NoahT** [comment]
@will-chung would you be alright looking into this issue with me?

**Comment by will-chung** [comment]
@NoahT I think the problem is in `tag.js`. The style element imports an icon from `/source/css/font/bootstrap-icons.css` but in deployment it should be `/cse110-w21-group7/css/font/bootstrap-icons.css` (as pictured below).

![image](https://user-images.githubusercontent.com/56745361/121433316-b0fe4880-c930-11eb-9852-52497c6a0144.png)
